version: 0.2

phases:

  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"

  pre_build:
    commands:
      - cd "/go/src/${PACKAGE}"
      - go test ./... # unit tests
      - go test -tags integration ./... # integration tests

  build:
    commands:
      - CGO_ENABLED=0 go build -ldflags="-s -w" -o app

  post_build:
    commands:
      - zip app.zip app
      - aws s3 cp app.zip s3://$ARTIFACT_BUCKET/$CODEBUILD_RESOLVED_SOURCE_VERSION/app.zip
      - echo "{\"hash\":\"$CODEBUILD_RESOLVED_SOURCE_VERSION\"}" > build-info.json

artifacts:
  files:
    - build-info.json
  discard-paths: yes